blueprint:
  name: Zigbee2MQTT Aqara Knob Temperature Adjustment with Button Press and Rotation
  description: 'Increase color temperature by turning the Aqara Knob right and pressing the button using Zigbee2MQTT'
  domain: automation
  input:
    knob:
      name: Aqara Knob
      description: The Aqara ZNXNKG02LM Knob entity
      selector:
        entity:
          integration: mqtt
          domain: sensor
    light_entity:
      name: Light entity
      description: The light to adjust the color temperature
      selector:
        entity:
          domain: light
    step_size:
      name: Step size
      description: "Temperature step to increase in Kelvin (Default: 50)"
      default: 50
      selector:
        number:
          min: 10
          max: 100
          unit_of_measurement: kelvin
  trigger:
    - platform: mqtt
      topic: zigbee2mqtt/!input knob/action
      payload: rotate_right
  condition:
    - condition: template
      value_template: "{{ trigger.payload_json.action == 'rotate_right' and trigger.payload_json.button == 'hold' }}"
  action:
    - service: light.turn_on
      target:
        entity_id: !input light_entity
      data_template:
        color_temp: >
          {% set current_temp = state_attr(input.light_entity, 'color_temp') %}
          {{ [current_temp + step_size, 500].min() }}
mode: single
